### PR TITLE
radiation model feature integration

### PR DESCRIPTION
**Pull request by ajbaird**
testing for integration practice

### CODE REVIEW

**Comment by StevenAWhite** [comment]
Austin can you move the main() function for the tutorial to the bottom of the primary howto source file and delete the _main version.

**Comment by StevenAWhite** [comment]
Austin, did you have time to push this change so we can complete the merge?

**Comment by ajbaird** [comment]
this includes the new radiation model feature

**Comment by StevenAWhite** [comment]
Merged /Closed/

**Review by StevenAWhite — COMMENTED** [review]
Accepted

**Pull request merged**
