### PR TITLE
F/abaird fentanyl paper

### PR DESCRIPTION
**Pull request by ajbaird**
- updates to opiod behavior in line with experimental data
- model updates to naloxone nasal deposition
- added some testing files
- finalizing the naloxone data generation how to for paper figures

### CODE REVIEW

**Comment by StevenAWhite** [comment]
Accepted - I need to verify the States and a few other things Monday morning and we will merge.

**Comment by ajbaird** [comment]
just posted one new commit to this branch just fyi, should have cleaned up the substance file in share and the .csv file

**Comment by StevenAWhite** [comment]
Austin, This should  be in shortly. It has a conflict that needs to be resolved I'll pull it down and push the rebase

**Comment by StevenAWhite** [comment]
Merged

**Pull request closed without merging**
